export const recipes = [
  {
    id: 1,
    name: 'Tortang Talong',
    category: 'Egg-Based',
    cost: 35,
    time: '15 mins',
    rating: 4.1,
    image: require('../assets/images/Tortang-Talong-1.jpg'),
    tags: ['Less than 50 pesos', 'Veggie Meal', 'Quick Prep'],
    ingredients: [
      { name: 'Eggplant (Talong)', amount: '2 pcs' },
      { name: 'Eggs', amount: '2 pcs' },
      { name: 'Onion', amount: '1 pc' },
      { name: 'Salt, Pepper', amount: 'to taste' },
    ],
    steps: [
      'Grill or boil the eggplant until soft and slightly charred.',
      'Peel off the skin carefully and flatten the eggplant using a fork.',
      'Beat the eggs in a bowl with onion, season with salt and pepper.',
      'Dip the flattened eggplant into the beaten egg mixture.',
      'Heat oil in a pan and fry until golden brown on both sides.',
    ],
    calories: '~220 kcal',
    servings: '1-2',
    difficulty: 'Easy',
    isFavorite: false,
  },
  {
    id: 2,
    name: 'Egg with Tomato',
    category: 'Egg-Based',
    cost: 25,
    time: '10 mins',
    rating: 4.0,
    image: require('../assets/images/Egg_with_Tomato.jpg'),
    tags: ['Less than 50 pesos', 'Quick Prep'],
    ingredients: [
      { name: 'Eggs', amount: '3 pcs' },
      { name: 'Tomato', amount: '2 pcs' },
      { name: 'Onion', amount: '1 pc' },
      { name: 'Salt, Pepper', amount: 'to taste' },
      { name: 'Cooking Oil', amount: '2 tbsp' },
    ],
    steps: [
      'Slice tomatoes and onion.',
      'Beat eggs in a bowl with salt and pepper.',
      'Saute onion and tomato in oil until soft.',
      'Pour in beaten eggs and stir until cooked.',
      'Serve hot with rice.',
    ],
    calories: '~180 kcal',
    servings: '2',
    difficulty: 'Easy',
    isFavorite: false,
  },
  {
    id: 3,
    name: 'Scrambled Eggs',
    category: 'Egg-Based',
    cost: 20,
    time: '5 mins',
    rating: 4.6,
    image: require('../assets/images/Scrambled_Egg.jpg'),
    tags: ['Less than 50 pesos', 'Quick Prep'],
    ingredients: [
      { name: 'Eggs', amount: '3 pcs' },
      { name: 'Butter', amount: '1 tbsp' },
      { name: 'Salt, Pepper', amount: 'to taste' },
      { name: 'Milk (optional)', amount: '2 tbsp' },
    ],
    steps: [
      'Crack eggs into a bowl and whisk with salt and pepper.',
      'Add milk if desired and whisk again.',
      'Melt butter in a pan over low heat.',
      'Pour in eggs and gently stir with a spatula.',
      'Remove from heat while still slightly wet — residual heat finishes cooking.',
    ],
    calories: '~150 kcal',
    servings: '1-2',
    difficulty: 'Easy',
    isFavorite: false,
  },
  {
    id: 4,
    name: 'Pancit Canton',
    category: 'Quick Prep',
    cost: 30,
    time: '20 mins',
    rating: 4.5,
    image: require('../assets/images/Pansit_Canton.webp'),
    tags: ['Less than 50 pesos', 'Quick Prep'],
    ingredients: [
      { name: 'Pancit Canton noodles', amount: '2 packs' },
      { name: 'Cabbage', amount: '1/4 pc' },
      { name: 'Carrot', amount: '1 pc' },
      { name: 'Soy sauce', amount: '2 tbsp' },
      { name: 'Garlic', amount: '3 cloves' },
    ],
    steps: [
      'Soak noodles in hot water for 5 minutes, drain.',
      'Saute garlic in oil until golden.',
      'Add carrots and cabbage, stir fry for 2 minutes.',
      'Add noodles and soy sauce, toss everything together.',
      'Add seasoning packets from noodle packs, mix well and serve.',
    ],
    calories: '~350 kcal',
    servings: '2',
    difficulty: 'Easy',
    isFavorite: false,
  },
  {
    id: 5,
    name: 'Ginisang Upo',
    category: 'Veggie Meals',
    cost: 30,
    time: '20 mins',
    rating: 4.2,
    image: require('../assets/images/Ginisang-Upo.jpg'),
    tags: ['Less than 50 pesos', 'Veggie Meal'],
    ingredients: [
      { name: 'Upo (bottle gourd)', amount: '1 pc' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Onion', amount: '1 pc' },
      { name: 'Tomato', amount: '1 pc' },
      { name: 'Patis or salt', amount: 'to taste' },
    ],
    steps: [
      'Peel and slice upo into small pieces.',
      'Saute garlic, onion, and tomato in oil.',
      'Add upo and stir fry for 2 minutes.',
      'Add 1/4 cup water, cover and simmer for 10 minutes.',
      'Season with patis or salt and serve with rice.',
    ],
    calories: '~90 kcal',
    servings: '2-3',
    difficulty: 'Easy',
    isFavorite: false,
  },
  {
    id: 6,
    name: 'Corned Beef with Potato',
    category: 'Canned Goods',
    cost: 55,
    time: '15 mins',
    rating: 4.0,
    image: require('../assets/images/Corned-Beef-Guisado-with-Potato.webp'),
    tags: ['Canned Goods', 'Quick Prep'],
    ingredients: [
      { name: 'Canned corned beef', amount: '1 can' },
      { name: 'Potato', amount: '2 pcs' },
      { name: 'Onion', amount: '1 pc' },
      { name: 'Garlic', amount: '3 cloves' },
      { name: 'Salt, Pepper', amount: 'to taste' },
    ],
    steps: [
      'Peel and dice potatoes into small cubes.',
      'Boil potatoes for 5 minutes until slightly tender.',
      'Saute garlic and onion in oil.',
      'Add corned beef and potatoes, mix well.',
      'Season with salt and pepper, cook for 5 more minutes.',
    ],
    calories: '~280 kcal',
    servings: '2',
    difficulty: 'Easy',
    isFavorite: false,
  },
  {
    id: 7,
    name: 'Adobong Sitaw',
    category: 'Veggie Meals',
    cost: 35,
    time: '22 mins',
    rating: 4.4,
    image: require('../assets/images/Adobong_Sitaw.avif'),
    tags: ['Less than 50 pesos', 'Veggie Meal'],
    ingredients: [
      { name: 'Sitaw (string beans)', amount: '1 bundle' },
      { name: 'Vinegar', amount: '3 tbsp' },
      { name: 'Soy sauce', amount: '3 tbsp' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Bay leaf', amount: '2 pcs' },
    ],
    steps: [
      'Cut sitaw into 2-inch pieces.',
      'Saute garlic in oil until golden.',
      'Add sitaw and stir fry for 2 minutes.',
      'Pour in vinegar and soy sauce, add bay leaf.',
      'Simmer for 10 minutes until tender. Serve with rice.',
    ],
    calories: '~100 kcal',
    servings: '2',
    difficulty: 'Easy',
    isFavorite: false,
  },
  {
    id: 8,
    name: 'Ginisang Sardinas',
    category: 'Canned Goods',
    cost: 40,
    time: '12 mins',
    rating: 4.1,
    image: require('../assets/images/Ginisang_Sardinas.jpg'),
    tags: ['Less than 50 pesos', 'Canned Goods'],
    ingredients: [
      { name: 'Canned sardines', amount: '1 can' },
      { name: 'Tomato', amount: '2 pcs' },
      { name: 'Onion', amount: '1 pc' },
      { name: 'Garlic', amount: '3 cloves' },
      { name: 'Chili (optional)', amount: '2 pcs' },
    ],
    steps: [
      'Saute garlic, onion and tomato.',
      'Add canned sardines with sauce.',
      'Add chili if desired.',
      'Simmer for 5 minutes, mashing lightly.',
      'Serve hot with rice.',
    ],
    calories: '~200 kcal',
    servings: '2',
    difficulty: 'Easy',
    isFavorite: false,
  },
];

export const categories = [
  { id: 'all', label: 'All', icon: 'grid' },
  { id: 'Egg-Based', label: 'Egg-Based', icon: '🍳' },
  { id: 'Veggie Meals', label: 'Veggie Meals', icon: '🥦' },
  { id: 'Canned Goods', label: 'Canned Goods', icon: '🥫' },
  { id: 'Quick Prep', label: 'Quick Prep', icon: '⚡' },
];